//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniversalGym.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UniversalGymEntities : DbContext
    {
        public UniversalGymEntities()
            : base("name=UniversalGymEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Address> Addresses { get; set; }
        public virtual DbSet<aspnet_Applications> aspnet_Applications { get; set; }
        public virtual DbSet<aspnet_Membership> aspnet_Membership { get; set; }
        public virtual DbSet<aspnet_Paths> aspnet_Paths { get; set; }
        public virtual DbSet<aspnet_PersonalizationAllUsers> aspnet_PersonalizationAllUsers { get; set; }
        public virtual DbSet<aspnet_PersonalizationPerUser> aspnet_PersonalizationPerUser { get; set; }
        public virtual DbSet<aspnet_Profile> aspnet_Profile { get; set; }
        public virtual DbSet<aspnet_Roles> aspnet_Roles { get; set; }
        public virtual DbSet<aspnet_SchemaVersions> aspnet_SchemaVersions { get; set; }
        public virtual DbSet<aspnet_Users> aspnet_Users { get; set; }
        public virtual DbSet<aspnet_WebEvent_Events> aspnet_WebEvent_Events { get; set; }
        public virtual DbSet<ContactInfo> ContactInfoes { get; set; }
        public virtual DbSet<FriendInvite> FriendInvites { get; set; }
        public virtual DbSet<GiveCredit> GiveCredits { get; set; }
        public virtual DbSet<GymInvoice> GymInvoices { get; set; }
        public virtual DbSet<GymPass> GymPasses { get; set; }
        public virtual DbSet<GymPhotoGallery> GymPhotoGalleries { get; set; }
        public virtual DbSet<Gym> Gyms { get; set; }
        public virtual DbSet<GymSchedule> GymSchedules { get; set; }
        public virtual DbSet<Log> Logs { get; set; }
        public virtual DbSet<PromoCode> PromoCodes { get; set; }
        public virtual DbSet<PromoCodesUsed> PromoCodesUseds { get; set; }
        public virtual DbSet<SearchRequest> SearchRequests { get; set; }
        public virtual DbSet<TypeState> TypeStates { get; set; }
        public virtual DbSet<TypeWeekDay> TypeWeekDays { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
