//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniversalGym.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class FriendInvite
    {
        public int FriendInviteId { get; set; }
        public Nullable<int> UserId { get; set; }
        public string FriendEmail { get; set; }
        public System.DateTime InviteDate { get; set; }
        public byte CreditsReward { get; set; }
    
        public virtual User User { get; set; }
    }
}
