//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniversalGym.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class GiveCredit
    {
        public int GiveCreditsId { get; set; }
        public int AmountToGiveNewUser { get; set; }
        public int UserIdToGiveCredits { get; set; }
        public System.DateTime DateTime { get; set; }
        public Nullable<int> UserIdWhoGiveCredits { get; set; }
        public Nullable<int> AmountToGiveReferer { get; set; }
        public Nullable<int> AmountCharged { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
