//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniversalGym.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gym
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Gym()
        {
            this.GymInvoices = new HashSet<GymInvoice>();
            this.GymPasses = new HashSet<GymPass>();
            this.GymPhotoGalleries = new HashSet<GymPhotoGallery>();
            this.GymSchedules = new HashSet<GymSchedule>();
        }
    
        public int GymId { get; set; }
        public string GymName { get; set; }
        public string GymInfo { get; set; }
        public System.DateTime ApplicationDate { get; set; }
        public bool IsActive { get; set; }
        public int CreditDollarValue { get; set; }
        public Nullable<System.Guid> GymGuid { get; set; }
        public bool IsApproved { get; set; }
        public System.Data.Entity.Spatial.DbGeography Position { get; set; }
        public string Url { get; set; }
        public string OwnerName { get; set; }
        public int PriceToCharge { get; set; }
        public string CurrentToken { get; set; }
        public string ScheduleUrl { get; set; }
        public string StripeUrl { get; set; }
        public Nullable<int> PublicContactInfoId { get; set; }
        public Nullable<int> OwnerContactInfoId { get; set; }
        public Nullable<System.DateTime> ActiveDate { get; set; }
        public bool badData { get; set; }
    
        public virtual ContactInfo ContactInfo { get; set; }
        public virtual ContactInfo ContactInfo1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GymInvoice> GymInvoices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GymPass> GymPasses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GymPhotoGallery> GymPhotoGalleries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GymSchedule> GymSchedules { get; set; }
    }
}
