//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniversalGym.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class GymPhotoGallery
    {
        public int GymPhotoGalleryId { get; set; }
        public int GymId { get; set; }
        public string Photo { get; set; }
        public bool IsCoverPhoto { get; set; }
        public bool badData { get; set; }
    
        public virtual Gym Gym { get; set; }
    }
}
