//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniversalGym.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class GymPass
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public int GymId { get; set; }
        public System.DateTime LocalDateBought { get; set; }
        public System.DateTime LocalDateExpired { get; set; }
        public int CreditsUsed { get; set; }
        public int AmountCharged { get; set; }
        public System.DateTime ServerTimeDateBought { get; set; }
        public int GymPassCost { get; set; }
    
        public virtual Gym Gym { get; set; }
        public virtual User User { get; set; }
    }
}
